name: Run flask App CI/CD Pipeline on push
on:
  push:
    branches:
     - 'main'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install requirements
      run:
       python -m pip install --upgrade pip
       pip install -r requirements.txt
    - name: Running flask app
      run: python app.py
      
